version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: yandex
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    restart: unless-stopped